### ISSUE TITLE
Create website

### ISSUE THREAD

**Issue by RamonGebben** [jlengrand/node-server-status#13]
If we want to promote the project more we should have a proper website and a demo application where people and interact with a sandboxed version of the application before considering to buy a licence.

**Comment by jlengrand** [comment]
What do you think is needed for this then? 

Do you want the app to allow for several users? Or something more simple where anybody can add his own link on a single instance of the webite?

**Comment by jlengrand** [comment]
I think at first we probably just need one instance of the site to run somewhere.

**Comment by RamonGebben** [comment]
Yes and maybe have a demo running somewhere that cleans itself every day. Just kill and remove container in a cron job or something. And then the website can just be a quick explanation of the " product" with a link to the demo and link to this repo.

**Comment by jlengrand** [comment]
i ll setup the vm when i get home tonihgt.
