### ISSUE TITLE
Get a more complete design and styling

### ISSUE THREAD

**Issue by jlengrand** [jlengrand/node-server-status#25]
Right now the application is very minimalistic (jsut a plus on hte top right)

It would be great to have some kind of background, the name of the application and a proper footer.

**Comment by jlengrand** [comment]
Something simple that can be done quickly and look good would be great

**Comment by RamonGebben** [comment]
Yes I will pick this up once I finish up moving to Redux and immutable.

**Comment by jlengrand** [comment]
How are we doing with redux? I'd really like to get that going

**Comment by RamonGebben** [comment]
I have redux in there and working but we are not actually using it right now.
I could finalise it and iterate over it in a different issue if you like.
